services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: daniespadel
      POSTGRES_USER: dp_user
      POSTGRES_PASSWORD: dp_pass
    ports:
      - "5432:5432"
    volumes:
      - dp_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  dp_pg_data:
