spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/daniespadel
    username: dp_user
    password: dp_pass
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  jwt:
    secret: "p7y1c0kq9Jv6LJ2q3gH7b0C1mZ8sQ5rTnY3wV6xZ2uP4aN9dR1eT6yU8oL4pQ2mS" 
    expirationMinutes: 60
