spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/daniespadel
    username: dp_user
    password: dp_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

app:
  jwt:
    secret: "pbm<a/]K8CO2QeNl,ZP|*crAx0v#TS{nj>_z1:u6=.i)!whRMg$(/4YIGH-.7q5~[V9}^`@DtEoB'dFXJs?kL3U&W%f+y;"
    expirationMinutes: 120
